---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: os-image-nvidia
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 44@sha256:3318ebff7eada58e23c3aa8dc84349638b109a866fcd6cb5e9e150687179e701  # You can pin to a specific version of Fedora as well

stages:
  - from-file: common-stages.yml

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: finpilot-setup-nvidia.yml